### ISSUE TITLE
Following instructions to clone, install and run don't work

### ISSUE THREAD

**Issue by brainlid** [janjarfalk/ionic2-angular2-ts-redux-boilerplate#1]
Performing a clean install (git clone, nvm use 4.2.6, npm install) fails.

I kept getting further by making changes like fixing ionic warnings for deprecated files. Had to do a `typings init`, `typings install` too.

Still at a point where it is failing because it prompted to install a default gulpfile.js config and now it is looking for /app/app.ts instead of the MyApp.ts file.

I'm just stuck. 

Can you try cloning to a fresh directory and can you get it working? Otherwise, if there are changes needed, can you direct me?

**Comment by janjarfalk** [comment]
A lot has happened to both Angular2 and Ionic2 in the last four months.
Can you please try this branch instead.

https://github.com/janjarfalk/ionic2-angular2-ts-redux-boilerplate/tree/ng2rc1

**Comment by janjarfalk** [comment]
The repo hadn't been updated for 4 months, but a lot had changed with both Ionic2 and Angular2.  The repo is now updated to work with the latest version of both Ionic2 and Angular2. It also uses the much improved WKWebView.

I just followed the new instructions...
```shell
git clone https://github.com/janjarfalk/ionic2-angular2-ts-redux-boilerplate.git
cd ionic2-angular2-ts-redux-boilerplate
nvm use 4.2.0 && npm install && ionic plugin add cordova-plugin-wkwebview-engine && ionic plugin add https://git-wip-us.apache.org/repos/asf/cordova-plugins.git#master:local-webserver

ionic run ios && ionic run ios
```

...and it worked for me.

**Comment by brainlid** [comment]
Verified that it works now with your recent changes. Thanks! Really looking forward to getting this exact technology stack to play nice!

**Comment by janjarfalk** [comment]
With some modifications (i.e. autoinclude sass-files instead of manually listing them in `app/theme/app.core.scss`) we are using this stack in production.

Let me know if you have any ideas on how to make it better.
